add_newline = false

format = "$directory $git_branch $git_status $cmd_duration $character"

[directory]
style = "blue"
truncation_length = 3

[git_branch]
symbol = "🌱 "
style = "yellow"

[git_status]
style = "red"

[character]
success_symbol = "[➜](green)"
error_symbol = "[✗](red)"

[cmd_duration]
format = "⏰ [$duration](bold yellow)"
